"""subreddit table

Revision ID: 3f83d28e1dbe
Revises: abdc96c7122c
Create Date: 2020-01-16 16:36:35.972223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f83d28e1dbe'
down_revision = 'abdc96c7122c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subreddit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subreddit_sub'), 'subreddit', ['sub'], unique=True)
    op.create_table('users_subreddits',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subreddit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_subreddits')
    op.drop_index(op.f('ix_subreddit_sub'), table_name='subreddit')
    op.drop_table('subreddit')
    # ### end Alembic commands ###
