"""tags table

Revision ID: abdc96c7122c
Revises: ad0b607a4a9f
Create Date: 2020-01-15 12:48:25.960963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdc96c7122c'
down_revision = 'ad0b607a4a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_text'), 'tag', ['text'], unique=True)
    op.create_table('users_tags',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_tags')
    op.drop_index(op.f('ix_tag_text'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
