"""email fields in user model

Revision ID: db57aaa2a7c6
Revises: 3f83d28e1dbe
Create Date: 2020-01-19 20:31:11.474581

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
from sqlalchemy.orm import Session
from app.models import User


# revision identifiers, used by Alembic.
revision = 'db57aaa2a7c6'
down_revision = '3f83d28e1dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_email_sent', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('send_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'send_email')
    op.drop_column('user', 'last_email_sent')
    # ### end Alembic commands ###
